import math

# screen
# SCREEN_WIDTH = 360
# SCREEN_HEIGHT = 640
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# ui size
FONT_SIZE_RATIO = 0.075
FONT_SIZE = round(max(SCREEN_WIDTH, SCREEN_HEIGHT) * FONT_SIZE_RATIO)
BUTTON_SIZE_RATIO = 0.2
BUTTON_OFFSET_RATIO = 1.5
BUTTON_WIDTH = round(max(SCREEN_WIDTH, SCREEN_HEIGHT) * BUTTON_SIZE_RATIO)
BUTTON_HEIGHT = round(BUTTON_WIDTH * 0.25)
BUTTON_FONT_SIZE = round(BUTTON_HEIGHT * 0.6)
SCROLL_BAR_OFFSET_RATIO = 12
SCROLL_BAR_WIDTH = BUTTON_WIDTH
SCROLL_BAR_HEIGHT = round(SCROLL_BAR_WIDTH * 0.03)
SCROLL_BAR_FONT_SIZE = SCROLL_BAR_HEIGHT * 3

# object
OBJECT_DICT = {
    'none': 0,
    'wall': 1,
    'body': 2,
    'feed': 3, 
}
OBJECT_OUTLINE_RATIO = 0.2

# color
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GRAY = (128, 128, 128)
LIGHT_GRAY = (200, 200, 200)

BODY_OUTLINE_COLOR = (59, 92, 70)
BODY_COLOR = (7, 255, 82)
FEED_OUTLINE_COLOR = (187, 113, 40)
FEED_COLOR = (255, 255, 15)
DIR_COLOR = (255, 255, 255)

# direction
DIR_ARROW_RATIO = 0.5
DIR_OFFSET_DICT = {
    'E': (1, 0),
    'W': (-1, 0),
    'S': (0, 1),
    'N': (0, -1)
}
DIR_ANGLE_DICT = {
# pygame.transform.rotate operates counterclockwise
    'E': 0,
    'W': 180,
    'S': 270,
    'N': 90
}

# etc
GRID_NUM = (20, 20)
GRID_ALPHA = 128
GRID_THICKNESS = 1 # grid line thickness of map
FEED_NUM = 3
MOVE_DELAY = 30 # frame
INIT_LENGTH = 3 # initial length of snake
MAP_OUTERLINE_THICKNESS = 1
GRID_OUTERLINE_THICKNESS = 3